const express = require('express')
const { authenticateToken } = require('../middlewares/authMiddleware')
const { validationMiddleware } = require('../middlewares/validationMiddleware')
const { checkoutSchema, updateOrderStatusSchema } = require('../schemas/orderSchema')
const { checkOut, getAllOrders, updateOrderStatus, getUserOrderHistory } = require('../controllers/orderController')
const { authorizeAdmin } = require('../middlewares/adminMiddleware')
const router = express.Router()
router.put('/', authenticateToken, validationMiddleware(checkoutSchema), checkOut)
router.get('/', authenticateToken, authorizeAdmin, getAllOrders)
router.put('/:id', authenticateToken, authorizeAdmin, validationMiddleware(updateOrderStatusSchema), updateOrderStatus)
router.get('/my-orders', authenticateToken, getUserOrderHistory)
module.exports = router